<div class="infor">
<div class="item">
<?php
    echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-middle-categories')
    ->toHtml()
?>
</div>

<!-- <p class="collapsibleTab" data-role="collapsible"><span class="title" data-role="trigger">Categories</span></p>
<ul class="content collapsibleContent" data-role="content">
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/43"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/42"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/44"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/45"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/46"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/47"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/48"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/49"}}</li>
<li><a href="#">Weber Premium Gas BBQs</a></li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/50"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/51"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_block.phtml" id_path="category/52"}}</li>
</ul> -->

<div class="item">
<?php
    echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-middle-infor')
    ->toHtml()
?>
<!-- <p class="collapsibleTab" data-role="collapsible"><span class="title" data-role="trigger">Why Burning Log?</span></p>
<ul class="content collapsibleContent" data-role="content">
<li><a href="#">About us</a></li>
<li><a href="#">All products</a></li>
<li><a href="#">Catalogues</a></li>
<li><a href="#">Contact us</a></li>
</ul> -->
</div>

<div class="item">
<?php
    echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-middle-policies')
    ->toHtml()
?>
<!-- <p><span class="title">Our Policies</span></p>
<ul class="content">
<li><a href="#">Terms and conditions</a></li>
<li><a href="#">Return policy</a></li>
<li><a href="#">Delivery and pick up policy</a></li>
<li><a href="#">Privacy policy</a></li>
</ul> -->
</div>
</div>