<?php
    echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-top')
    ->toHtml()
?>
<!-- <div class="item"><a href="#">
<i class="fas fa-truck"></i>
<span>We ship australia wide!</a>
</div>

<div class="item"><a href="#">
<i class="fas fa-map-marker-alt"></i>
<span>Find a store</span></a></div>

<div class="item"><a href="#">
<i class="fas fa-dollar-sign"></i>
<span>Money back guarantee<span></a></div>

<div class="item"><a href="#">
<i class="fas fa-envelope"></i>
<span>Contact us</span></a></div> -->