<div class="footer-showroom left">
    <?php
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-showroom-left')
        ->toHtml()
    ?>
</div>
<div class="footer-showroom center">
    <?php
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-showroom-center')
        ->toHtml()
    ?>
</div>
<div class="footer-showroom right">
    <?php
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-showroom-right')
        ->toHtml()
    ?>
</div>